### ISSUE TITLE
Use whitespace-insensitive diff as default

### ISSUE THREAD

**Issue by nathanchrs** [aguss787/FreeOJ#12]
Use 'diff -qb %s %s' (case-insensitive diff) as default diff command in grader/grader.js line 51

**Comment by aguss787** [comment]
diff -qb masih jadi temporary solution.
untuk beberapa kasus cara seperti ini masih salah.

pada mulanya bug ini ditemukan saat menjudge soal yang memiliki output lebih dari 1 baris.
dan file dicek manual dan sama, tp diff mereturn berbeda
"mungkin" karena perbedaan /n dan /r/n
